# Generated by Django 4.2.2 on 2023-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Forms_detail',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('admission_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('image', models.ImageField(upload_to='img/students/')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=200)),
                ('phone_number', models.IntegerField()),
                ('level', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True, max_length=30)),
                ('residential_address', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending Approval', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application_Form_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('application_position', models.CharField(max_length=200)),
                ('certificate', models.ImageField(unique=True, upload_to='img/teachers/')),
                ('work_experience', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=200)),
                ('duration_of_work', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=20)),
                ('status', models.CharField(default='Pending Approval', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Payment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('total_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('amount_left', models.IntegerField(default=0)),
            ],
        ),
    ]
