# Generated by Django 4.2.2 on 2023-07-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_payment_details',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentregisteration'),
        ),
    ]
