# Generated by Django 4.2.2 on 2023-07-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_teacherregisteration_subject'),
        ('administrator', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(to='authentication.studentregisteration'),
        ),
    ]
