# Generated by Django 4.2.2 on 2023-07-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_teacherregisteration_subject'),
        ('administrator', '0004_remove_course_student_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered_students',
            field=models.ManyToManyField(default='None', related_name='registerd_students', to='authentication.studentregisteration'),
        ),
    ]
